project:
  type: website

website:
  title: "ISSS608 Visual Analytics And Applications"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu: 
          - text: "Hands-on Exercise 1"
            href: "hands-on_exercise1.qmd"  
          - text: "Hands-on Exercise 2"
            href: "hands_on_exercise2.qmd"  
          - text: "Hands-on Exercise 3a"
            href: "hands-on_exercise3_a.qmd"
          - text: "Hands-on Exercise 3b"
            href: "hands-on_exercise3_b.qmd"
          - text: "Hands-on Exercise 4a"
            href: "hands-on_exercise4a.qmd"
          - text: "Hands-on Exercise 4b"
            href: "hands-on_exercise4b.qmd"
          - text: "Hands-on Exercise 4c"
            href: "hands-on_exercise4c.qmd"
          - text: "Hands-on Exercise 4d"
            href: "hands-on_exercise4d.qmd"
          - text: "Hands-on Exercise 5"
            href: "hands-on_exercise5.qmd"
          - text: "Hands-on Exercise 6"
            href: "hands-on_exercise6.qmd"  
      - text: "In-class Exercises"
        menu:
          - text: "In-class Exercise 1"
            href: "In_class_Ex/In_class_Ex01/In_class_Ex01.html"  
      - text: "Take-home Exercises"
        menu:
          - text: "Take-home Exercises 1"
            href: "take-home_exercise1.qmd"  
    right: 
      - text: "Home"
        href: index.html
      - text: "About"
        href: about.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2 

editor: visual

output-dir: _site
